# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



stages:
  - publish


variables:
    # Fix wrong permissions for application image and instance user data due to runner setting "umask 0000" before
    # cloning the repository.
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: 'true'



# 
# Jobs.
#-----------------------------------------------------------------------------------------------------------------------
publishTerraformModule:
    stage: publish
    
    image: curlimages/curl:latest
    
    variables:
        moduleName: ${CI_PROJECT_NAME}
        moduleSystem: aws
        moduleVersion: ${CI_COMMIT_TAG}
        moduleArchive: ${moduleName}-${moduleSystem}-${moduleVersion}.tgz
        tokenHeader: 'JOB-TOKEN: ${CI_JOB_TOKEN}'
    
    script:
      - tar -vczf ${moduleArchive} --exclude=./.git .
      - curl
            --fail-with-body
            --location
            --header "${tokenHeader}"
            --upload-file ${moduleArchive}
            ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/terraform/modules/${moduleName}/${moduleSystem}/${moduleVersion}/file
    
    rules:
      - if: $CI_COMMIT_TAG