include:
  - component: gitlab.com/vaz-projects/gitlab/sane-workflow@1.2.0
  - component: gitlab.com/vaz-projects/gitlab/stages@1.2.0
  - component: gitlab.com/vaz-projects/gitlab/terraform-registry@1.2.0
    inputs:
        provider: external
        name: user-data
  - component: gitlab.com/vaz-projects/gitlab/release@1.2.0



variables:
    # Fix wrong permissions for user data due to runner setting "umask 0000" before
    # cloning the repository.
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: 'true'